### ISSUE TITLE
DB Week 3 Feedback

### ISSUE THREAD

**Issue by orhantoy** [Ekamba/hyf-homework#1]
Hi @Ekamba :v:

Nice job 👍 I found a few minor things:

- Remember to have the same type for the foreign key as the primary key from `meals`:
  https://github.com/Ekamba/hyf-homework/blob/6d224d3ac2b2ddd71b1f7b2b96adfef67807fcf8/databases/week3/mealSharing.sql#L19
  https://github.com/Ekamba/hyf-homework/blob/6d224d3ac2b2ddd71b1f7b2b96adfef67807fcf8/databases/week3/mealSharing.sql#L28
- Also, you seem to be missing foreign key constraints for the aforementioned ⬆️ fields.
- You shouldn't need `Review_Reservation` and `Review_Meal`:
  https://github.com/Ekamba/hyf-homework/blob/6d224d3ac2b2ddd71b1f7b2b96adfef67807fcf8/databases/week3/mealSharing.sql#L34-L48
- All the basic queries look correct, nice job! 💯 Awesome job putting in actual meals as it always important with good test data.
- I think you're close to having the right solution here but you need to aggregate the `number_of_guests` column and check that against `Meal.max_reservations`.
  https://github.com/Ekamba/hyf-homework/blob/6d224d3ac2b2ddd71b1f7b2b96adfef67807fcf8/databases/week3/mealSharing.sql#L489-L495
- I think using `LIKE` would be a bit cleaner but your version might also work.
  https://github.com/Ekamba/hyf-homework/blob/6d224d3ac2b2ddd71b1f7b2b96adfef67807fcf8/databases/week3/mealSharing.sql#L497-L503
- The last query is missing:
  https://github.com/Ekamba/hyf-homework/blob/6d224d3ac2b2ddd71b1f7b2b96adfef67807fcf8/databases/week3/mealSharing.sql#L534

Please feel free to ask questions in here so you can get the remaining things done.

**Comment by Ekamba** [comment]
HI orhantoy, Thank you a lot for reviewing my homework. I will correct it as you said.
Can you check it again, if my correction is good anough?

**Comment by orhantoy** [comment]
Hi @Ekamba :v:

You're getting close but there are still a few missing things:

- Foreign key constraints are missing
- The query for "Get meals that still has available reservations" is not correct
- The query for "Sort all meals by average number of stars in the reviews" is also not correct

For both mentioned queries you need to use some aggregation functions, so if you need help with this please let me know.

**Comment by Ekamba** [comment]
HI there , Thank again to look into my homework, I think I need help for what you mentioned. If it is possible to give more details I will appreciate.
