### ISSUE TITLE
Homework Review - Node Week 1

### ISSUE THREAD

**Issue by jawkha** [Ekamba/hyf-homework#2]
There are typos and minor mistakes here and there due to which the app keeps crashing. Please remember to test your app first to verify that it works as expected before making it available for review.

Please fix these issues and let me know so I can review it again.

**Comment by Ekamba** [comment]
HI Jawkha, Thank you for reviewing my homework. I will check and correct it.

**Comment by Ekamba** [comment]
HI again Jawkha, I have made some changes. Can you check ones more ? Thank you.
